imports:
- path: deployment.jinja
- path: ingress.jinja

resources:
- name: thanos
  type: deployment.jinja
  properties:
    cluster: ultron
    image: gcr.io/bachelor-2020/hello-world:1.4
    port: 8080
    ingress: false