# Example # When in use change to deployment.yaml and place in repo

imports:
- path: deployment.jinja
- path: ingress.jinja

resources:
- name: thanos
  type: deployment.jinja
  properties:
    cluster: ultron
    image: gcr.io/bachelor-2020/test-rest:latest
    port: 8080
    ingress: false
    sql: true
    dbname: db4
    region: europe-west1
    project: bachelor-2020
    sqlport: 3306



#- name: joker
#  type: sql.jinja
#  properties:
#    region: europe-west1-b
#    tier: db-f1-micro
#    charset: utf8
#    userName: testuser
#    password: erlend
#    hostName: joker-host
